# Generated by Django 6.0.1 on 2026-01-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
