# Generated by Django 5.2.9 on 2026-01-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('category', models.TextField(max_length=25)),
                ('stock', models.IntegerField(max_length=2)),
            ],
        ),
    ]
