name: Django CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        cd ORMandShell
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        cd ORMandShell
        python manage.py migrate

    - name: Run Server Check
      run: |
        cd ORMandShell
        python manage.py check